# This file was first automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 06:13:03 2018 from module list in Acme::CPANLists::PERLANCAR::Self::CLIWithSubcommands version 0.003.

package Acme::CPANModules::PERLANCAR::MyCLIWithSubcommands;

use strict;

# AUTHORITY
# DATE
# DIST
# VERSION

our $LIST = {
  entries => [
               { module => "App::AcmeCpanlists", scripts => ["acme-cpanlists"] },
               { module => "App::CPAN::Changes", scripts => ["cpan-changes"] },
               { module => "App::dux", scripts => ["dux"] },
               { module => "App::GitUtils", scripts => ["gu"] },
               { module => "App::lcpan", scripts => ["lcpan"] },
               { module => "App::pause", scripts => ["pause"] },
               { module => "App::PDRUtils", scripts => ["pdrutil", "pdrutil-multi"] },
               { module => "App::reposdb", scripts => ["reposdb"] },
               { module => "App::rimetadb", scripts => ["rimetadb"] },
               { module => "App::shcompgen", scripts => ["shcompgen"] },
               { module => "App::short", scripts => ["short"] },
               { module => "App::TableDataUtils", scripts => ["gen-rand-table"] },
               { module => "App::perlmv::u", scripts => ["perlmv-u"] },
               { module => "App::trash::u", scripts => ["trash-u"] },
               { module => "App::upf", scripts => ["upf"] },
               { module => "App::wp::xmlrpc", scripts => ["wp-xmlrpc"] },
               { module => "Git::Bunch", scripts => ["gitbunch"] },
               { module => "phpBB2::Simple", scripts => ["phpbb2"] },
             ],
  summary => "List of distributions that contain CLI scripts with subcommands",
};

1;
# ABSTRACT: Distributions that contain CLI scripts with subcommands
